#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <cstring>
#include <sstream> 
#include <fstream>
#include <math.h> 
#include <float.h>
#include <unistd.h>
#include <string.h> 
#include <vector> 
#include <sys/time.h>
#include <sys/types.h>
#include <strings.h>
#include <string>
#include "InputTest.h"
#include "Video.h"
#include "LogFile.h"